services:
  - type: web
    name: bookreview-platform
    env: php
    region: oregon
    branch: main
    rootDir: ./
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false  # <-- thêm thủ công trong dashboard
      - key: DB_PORT
        value: 24322
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
